# Generated by Django 5.1.15 on 2026-10-03 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0007_koordinat_klinik"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KnownDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(unique=True, verbose_name="alamat IP"),
                ),
                (
                    "name",
                    models.CharField(max_length=80, verbose_name="nama perangkat"),
                ),
                (
                    "is_clinic_device",
                    models.BooleanField(
                        default=False,
                        help_text="Centang untuk PC/tablet klinik. Jejak dari perangkat ini berlabel Kuat.",
                        verbose_name="perangkat milik klinik",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="catatan"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cabang tempat perangkat ini berada. Kosong bila berpindah-pindah.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="known_devices",
                        to="core.clinic",
                    ),
                ),
            ],
            options={
                "verbose_name": "perangkat dikenal",
                "verbose_name_plural": "perangkat dikenal",
                "ordering": ("-is_clinic_device", "name"),
            },
        ),
        migrations.CreateModel(
            name="PresenceStamp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("LOGIN", "Masuk aplikasi"),
                            ("BUKA_HARI", "Buka hari"),
                            ("TUTUP_HARI", "Tutup hari"),
                            ("CHECKLIST", "Isi checklist"),
                            ("KAS", "Hitung kas"),
                            ("KAS_AJUKAN", "Ajukan kas"),
                            ("PROGRES", "Lapor progres"),
                            ("AJUKAN", "Ajukan selesai"),
                        ],
                        max_length=12,
                        verbose_name="kejadian",
                    ),
                ),
                ("entity_type", models.CharField(blank=True, max_length=40)),
                ("entity_id", models.PositiveIntegerField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "ip_prefix",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=64,
                        verbose_name="kelompok IP",
                    ),
                ),
                (
                    "network",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("TAILSCALE", "Perangkat Tailscale"),
                            ("LOKAL", "Jaringan lokal"),
                            ("PUBLIK", "Internet umum"),
                            ("", "Tidak diketahui"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "device_kind",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="jenis perangkat"
                    ),
                ),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                (
                    "geo_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("OK", "Lokasi didapat"),
                            ("DITOLAK", "Izin lokasi ditolak"),
                            ("TIDAK_TERSEDIA", "Lokasi tidak tersedia"),
                            ("", "Tidak diminta"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
                (
                    "accuracy_m",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="akurasi (m)"
                    ),
                ),
                (
                    "distance_m",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="jarak ke klinik (m)"
                    ),
                ),
                (
                    "confidence",
                    models.CharField(
                        choices=[
                            ("KUAT", "Kuat"),
                            ("SEDANG", "Sedang"),
                            ("LEMAH", "Lemah"),
                        ],
                        default="LEMAH",
                        max_length=8,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="alasan label"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="presence_stamps",
                        to="core.clinic",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stamps",
                        to="jejak.knowndevice",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presence_stamps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "jejak kehadiran",
                "verbose_name_plural": "jejak kehadiran",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["clinic", "ip_prefix", "confidence"],
                        name="jejak_prese_clinic__2c1ac3_idx",
                    )
                ],
            },
        ),
    ]
