# Generated by Django 5.1.15 on 2026-10-03 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_clinic_profile_data"),
        ("owner", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ownerrequest",
            name="clinic",
            field=models.ForeignKey(
                blank=True,
                help_text="Kosong bila lintas cabang.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="owner_requests",
                to="core.clinic",
            ),
        ),
        migrations.AddField(
            model_name="ownerrequest",
            name="kind",
            field=models.CharField(
                choices=[("PERMINTAAN", "Permintaan"), ("TEMUAN", "Temuan")],
                default="PERMINTAAN",
                max_length=12,
                verbose_name="jenis",
            ),
        ),
        migrations.AddField(
            model_name="ownerrequest",
            name="urgent",
            field=models.BooleanField(default=False, verbose_name="mendesak"),
        ),
        migrations.AlterField(
            model_name="ownerrequest",
            name="target_date",
            field=models.DateField(blank=True, null=True, verbose_name="target"),
        ),
    ]
