# Generated by Django 5.1.15 on 2026-10-06 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_temuan_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerrequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='dinyatakan selesai'),
        ),
        migrations.AddField(
            model_name='ownerrequest',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ownerrequest',
            name='plan_title',
            field=models.CharField(blank=True, help_text="Nama penanganan temuan dari Direktur, mis. 'Membuat alur untuk temuan X'.", max_length=200, verbose_name='task besar'),
        ),
    ]
