# Generated by Django 5.1.15 on 2026-10-07 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_task_kendala'),
        ('direktur', '0007_summary_dua_arah'),
        ('owner', '0004_tutup_temuan_lama'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usulan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('PERSETUJUAN', 'Minta persetujuan'), ('LAPORAN', 'Laporan masalah/risiko')], max_length=12, verbose_name='jenis')),
                ('title', models.CharField(max_length=200, verbose_name='judul')),
                ('description', models.TextField(verbose_name='uraian')),
                ('amount', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='nominal anggaran (Rp)')),
                ('needed_by', models.DateField(blank=True, null=True, verbose_name='perlu jawaban sebelum')),
                ('status', models.CharField(choices=[('MENUNGGU', 'Menunggu keputusan'), ('DISETUJUI', 'Disetujui'), ('DITOLAK', 'Ditolak'), ('RAPAT', 'Dibawa ke rapat'), ('TERKIRIM', 'Terkirim'), ('DIBACA', 'Sudah dibaca'), ('DIBATALKAN', 'Dibatalkan')], max_length=12)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True, verbose_name='catatan keputusan')),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True, verbose_name='alasan pembatalan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('clinic', models.ForeignKey(blank=True, help_text='Kosong bila lintas cabang.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usulan', to='core.clinic')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usulan_dibuat', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('decision', models.ForeignKey(blank=True, help_text='Perkara rapat bila usulan dibawa ke rapat.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usulan', to='direktur.decision')),
                ('read_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'usulan',
                'verbose_name_plural': 'usulan',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='UsulanCatatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(verbose_name='catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usulan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='owner.usulan')),
            ],
            options={
                'verbose_name': 'catatan usulan',
                'verbose_name_plural': 'catatan usulan',
                'ordering': ('created_at', 'id'),
            },
        ),
    ]
