# Generated by Django 5.1.15 on 2026-10-07 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0005_usulan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerrequest',
            name='proposed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ownerrequest',
            name='proposed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ownerrequest',
            name='proposed_reason',
            field=models.TextField(blank=True, verbose_name='alasan usulan target'),
        ),
        migrations.AddField(
            model_name='ownerrequest',
            name='proposed_target',
            field=models.DateField(blank=True, null=True, verbose_name='usulan target'),
        ),
    ]
