# Generated by Django 5.1.15 on 2026-10-08 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_kategori_bintang_task'),
        ('owner', '0006_usulan_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerrequest',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owner_requests', to='core.taskcategory', verbose_name='kategori'),
        ),
    ]
