# Generated by Django 5.1.15 on 2026-10-05 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_uid', models.CharField(max_length=20, unique=True, verbose_name='ID di mesin')),
                ('device_label', models.CharField(blank=True, help_text='Ejaan nama persis seperti tercetak di ekspor mesin.', max_length=120, verbose_name='nama di mesin')),
                ('active', models.BooleanField(default=True, verbose_name='aktif')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_devices', to=settings.AUTH_USER_MODEL, verbose_name='staf')),
            ],
            options={
                'verbose_name': 'ID mesin absensi',
                'verbose_name_plural': 'ID mesin absensi',
                'ordering': ('device_uid',),
            },
        ),
        migrations.CreateModel(
            name='AttendanceImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='nama berkas')),
                ('checksum', models.CharField(db_index=True, max_length=64, verbose_name='sidik berkas')),
                ('period_start', models.DateField(blank=True, null=True, verbose_name='periode mulai')),
                ('period_end', models.DateField(blank=True, null=True, verbose_name='periode selesai')),
                ('imported_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('rows_read', models.PositiveIntegerField(default=0, verbose_name='baris hari terbaca')),
                ('punches_created', models.PositiveIntegerField(default=0, verbose_name='cap baru')),
                ('punches_skipped', models.PositiveIntegerField(default=0, verbose_name='cap sudah ada')),
                ('warnings', models.JSONField(blank=True, default=list, verbose_name='peringatan')),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='diimpor oleh')),
            ],
            options={
                'verbose_name': 'impor absensi',
                'verbose_name_plural': 'impor absensi',
                'ordering': ('-imported_at',),
            },
        ),
        migrations.CreateModel(
            name='AttendancePunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_date', models.DateField(db_index=True, verbose_name='tanggal shift')),
                ('occurred_at', models.DateTimeField(verbose_name='waktu cap')),
                ('kind', models.CharField(choices=[('MASUK', 'Masuk'), ('KELUAR', 'Keluar'), ('TIDAK_PASTI', 'Belum pasti masuk atau keluar')], max_length=12, verbose_name='jenis')),
                ('source', models.CharField(choices=[('FINGERPRINT', 'Mesin sidik jari'), ('MANUAL', 'Koreksi manual')], default='FINGERPRINT', max_length=12, verbose_name='sumber')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='punches', to='absensi.attendancedevice', verbose_name='ID mesin')),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='punches', to='absensi.attendanceimport', verbose_name='berkas impor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_punches', to=settings.AUTH_USER_MODEL, verbose_name='staf')),
            ],
            options={
                'verbose_name': 'cap absensi',
                'verbose_name_plural': 'cap absensi',
                'ordering': ('shift_date', 'occurred_at'),
                'indexes': [models.Index(fields=['user', 'shift_date'], name='absensi_att_user_id_b24f7e_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'occurred_at'), name='uniq_punch_user_waktu')],
            },
        ),
    ]
