# Generated by Django 5.1.15 on 2026-10-05 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancedevice',
            name='recording_only',
            field=models.BooleanField(default=False, help_text='Capnya disimpan dan bisa dilihat, tetapi tidak masuk papan skor dan tidak menghasilkan daftar pengecualian. Untuk staf di luar skema shift dua cabang.', verbose_name='rekam saja, tanpa penilaian'),
        ),
    ]
