# Generated by Django 5.1.15 on 2026-10-05 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0002_attendancedevice_recording_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancepunch',
            name='tz_mesin',
            field=models.CharField(blank=True, help_text='"I" atau "II": jendela shift yang dipakai mesin untuk cap ini, dibaca dari kolom tempat jamnya ditulis di ekspor. Kosong bila kolomnya tidak membedakan shift (cap masuk selalu begitu).', max_length=2, verbose_name='jendela shift mesin'),
        ),
    ]
