# Generated by Django 5.1.15 on 2026-09-10 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, verbose_name='kode')),
                ('name', models.CharField(max_length=150, verbose_name='nama')),
                ('category', models.CharField(blank=True, choices=[('FASILITAS', 'Fasilitas'), ('ALAT_MEDIS', 'Alat medis'), ('IT', 'IT'), ('LISTRIK', 'Listrik'), ('AIR', 'Air'), ('FURNITUR', 'Furnitur'), ('KESELAMATAN', 'Keselamatan'), ('LAINNYA', 'Lainnya')], max_length=20)),
                ('location', models.CharField(blank=True, max_length=150, verbose_name='lokasi')),
                ('do_not_use', models.BooleanField(default=False, verbose_name='jangan digunakan')),
                ('do_not_use_reason', models.CharField(blank=True, max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='core.clinic')),
            ],
            options={
                'verbose_name': 'aset',
                'verbose_name_plural': 'aset',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('KOMPLAIN', 'Komplain'), ('MASUKAN', 'Masukan/saran'), ('KERUSAKAN', 'Kerusakan')], db_index=True, max_length=10, verbose_name='tipe')),
                ('number', models.CharField(max_length=30, unique=True, verbose_name='nomor')),
                ('title', models.CharField(max_length=200, verbose_name='ringkasan')),
                ('description', models.TextField(blank=True, verbose_name='uraian')),
                ('category', models.CharField(blank=True, max_length=60, verbose_name='kategori')),
                ('severity', models.CharField(choices=[('RENDAH', 'Rendah'), ('SEDANG', 'Sedang'), ('TINGGI', 'Tinggi'), ('KRITIS', 'Kritis')], default='SEDANG', max_length=10, verbose_name='tingkat')),
                ('status', models.CharField(choices=[('BARU', 'Baru'), ('DITINJAU', 'Ditinjau'), ('DITUGASKAN', 'Ditugaskan'), ('DALAM_PROSES', 'Dalam proses'), ('MENUNGGU_PIHAK_LAIN', 'Menunggu pihak lain'), ('SELESAI', 'Selesai'), ('DIVERIFIKASI', 'Diverifikasi'), ('DITUTUP', 'Ditutup'), ('DIPERTIMBANGKAN', 'Dipertimbangkan'), ('DIRENCANAKAN', 'Direncanakan'), ('DITERAPKAN', 'Diterapkan'), ('DITOLAK', 'Ditolak'), ('DITRIASE', 'Ditriase'), ('DALAM_PERBAIKAN', 'Dalam perbaikan'), ('MENUNGGU_VENDOR', 'Menunggu vendor/komponen')], db_index=True, default='BARU', max_length=20)),
                ('is_restricted', models.BooleanField(default=False, verbose_name='terbatas')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='anonim terhadap staf biasa')),
                ('reporter_source', models.CharField(blank=True, choices=[('PASIEN', 'Pasien'), ('KELUARGA', 'Keluarga pasien'), ('STAF', 'Staf'), ('LAINNYA', 'Lainnya')], max_length=10)),
                ('reporter_contact', models.CharField(blank=True, max_length=120, verbose_name='kontak pelapor')),
                ('channel', models.CharField(blank=True, choices=[('LANGSUNG', 'Langsung'), ('TELEPON', 'Telepon'), ('CHAT', 'Chat'), ('FORMULIR', 'Formulir'), ('LAINNYA', 'Lainnya')], max_length=10)),
                ('occurred_at', models.DateTimeField(blank=True, null=True, verbose_name='waktu kejadian')),
                ('followup_preference', models.CharField(blank=True, max_length=200, verbose_name='preferensi tindak lanjut')),
                ('benefit', models.TextField(blank=True, verbose_name='manfaat/dampak')),
                ('location', models.CharField(blank=True, max_length=150, verbose_name='lokasi')),
                ('impact', models.CharField(blank=True, choices=[('NORMAL', 'Tetap dapat digunakan'), ('TERBATAS', 'Penggunaan terbatas'), ('TIDAK_DAPAT', 'Tidak dapat digunakan'), ('RISIKO_KESELAMATAN', 'Risiko keselamatan')], max_length=20)),
                ('repair_action', models.TextField(blank=True, verbose_name='tindakan perbaikan')),
                ('repair_vendor', models.CharField(blank=True, max_length=150, verbose_name='pelaksana/vendor')),
                ('repair_cost', models.BigIntegerField(blank=True, null=True, verbose_name='biaya (Rp)')),
                ('repaired_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_summary', models.TextField(blank=True, verbose_name='ringkasan penyelesaian')),
                ('closed_reason', models.TextField(blank=True, verbose_name='alasan penutupan/penolakan')),
                ('source_ref', models.CharField(blank=True, max_length=60)),
                ('due_at', models.DateTimeField(blank=True, null=True, verbose_name='target selesai')),
                ('assign_due_at', models.DateTimeField(blank=True, null=True, verbose_name='target penugasan')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='issues.asset')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='core.clinic')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues_created', to=settings.AUTH_USER_MODEL)),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='issues.issue')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'catatan issue',
                'verbose_name_plural': 'catatan issue',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='IssueAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues_assigned', to=settings.AUTH_USER_MODEL)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_assignments', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='issues.issue')),
            ],
            options={
                'verbose_name': 'penugasan issue',
                'verbose_name_plural': 'penugasan issue',
                'ordering': ('-assigned_at',),
            },
        ),
        migrations.CreateModel(
            name='IssueUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(blank=True, max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_updates', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='issues.issue')),
            ],
            options={
                'verbose_name': 'riwayat issue',
                'verbose_name_plural': 'riwayat issue',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(fields=('clinic', 'code'), name='uniq_asset_code'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['issue_type', 'status'], name='issues_issu_issue_t_c88a41_idx'),
        ),
    ]
