# Generated by Django 5.1.15 on 2026-10-07 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0009_task_kendala'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nama project')),
                ('description', models.TextField(blank=True, verbose_name='uraian')),
                ('target_date', models.DateField(blank=True, null=True, verbose_name='target')),
                ('status', models.CharField(choices=[('AKTIF', 'Berjalan'), ('SELESAI', 'Selesai'), ('DIBATALKAN', 'Dibatalkan')], default='AKTIF', max_length=12)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('close_note', models.TextField(blank=True, verbose_name='catatan penutupan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(blank=True, help_text='Kosong bila lintas cabang.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='core.clinic')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('co_leaders', models.ManyToManyField(blank=True, related_name='co_led_projects', to=settings.AUTH_USER_MODEL, verbose_name='Co-project leader')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='led_projects', to=settings.AUTH_USER_MODEL, verbose_name='Project leader')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'project',
                'ordering': ('-created_at',),
            },
        ),
    ]
