# Generated by Django 5.1.15 on 2026-09-10 17:43

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nama')),
                ('code', models.SlugField(max_length=32, unique=True, verbose_name='kode')),
                ('address', models.TextField(blank=True, verbose_name='alamat')),
                ('timezone_name', models.CharField(default='Asia/Jakarta', max_length=64, verbose_name='zona waktu')),
                ('open_time', models.TimeField(default='12:00', verbose_name='jam buka')),
                ('close_time', models.TimeField(default='21:00', verbose_name='jam tutup')),
                ('active', models.BooleanField(default=True, verbose_name='aktif')),
            ],
            options={
                'verbose_name': 'klinik',
                'verbose_name_plural': 'klinik',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='judul')),
                ('description', models.TextField(blank=True, verbose_name='uraian')),
                ('source_type', models.CharField(max_length=40, verbose_name='modul sumber')),
                ('source_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='id sumber')),
                ('source_label', models.CharField(blank=True, max_length=120, verbose_name='label sumber')),
                ('priority', models.CharField(choices=[('RENDAH', 'Rendah'), ('SEDANG', 'Sedang'), ('TINGGI', 'Tinggi'), ('KRITIS', 'Kritis')], default='SEDANG', max_length=10)),
                ('status', models.CharField(choices=[('BARU', 'Baru'), ('DIKERJAKAN', 'Dikerjakan'), ('SELESAI', 'Selesai'), ('BATAL', 'Batal')], default='BARU', max_length=12)),
                ('due_at', models.DateTimeField(blank=True, null=True, verbose_name='target waktu')),
                ('progress_note', models.TextField(blank=True, verbose_name='catatan progres')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_items_created', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_items', to=settings.AUTH_USER_MODEL)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='core.clinic')),
            ],
            options={
                'verbose_name': 'action item',
                'verbose_name_plural': 'action item',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(db_index=True, max_length=40)),
                ('entity_id', models.PositiveIntegerField(db_index=True)),
                ('file', models.FileField(max_length=255, upload_to=core.models.attachment_upload_to)),
                ('original_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('size_bytes', models.PositiveIntegerField()),
                ('sensitive', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'lampiran',
                'verbose_name_plural': 'lampiran',
                'ordering': ('-uploaded_at',),
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='core_attach_entity__eff668_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClinicConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, verbose_name='kunci')),
                ('value', models.JSONField(verbose_name='nilai')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='keterangan')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='core.clinic')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'konfigurasi klinik',
                'verbose_name_plural': 'konfigurasi klinik',
                'ordering': ('key',),
                'constraints': [models.UniqueConstraint(fields=('clinic', 'key'), name='uniq_clinic_config_key')],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='tanggal')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='keterangan')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='core.clinic')),
            ],
            options={
                'verbose_name': 'hari libur',
                'verbose_name_plural': 'hari libur',
                'ordering': ('-date',),
                'constraints': [models.UniqueConstraint(fields=('clinic', 'date'), name='uniq_clinic_holiday')],
            },
        ),
        migrations.CreateModel(
            name='OperationalDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='tanggal operasional')),
                ('shift', models.CharField(blank=True, default='', max_length=40, verbose_name='shift')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPENING_IN_PROGRESS', 'Pembukaan berjalan'), ('READY', 'Siap'), ('READY_WITH_ISSUES', 'Siap dengan catatan'), ('OPEN', 'Buka'), ('CLOSING', 'Penutupan'), ('CLOSED', 'Tutup')], default='DRAFT', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('ready_exception_reason', models.TextField(blank=True, verbose_name='alasan siap dengan catatan')),
                ('close_override_reason', models.TextField(blank=True, verbose_name='alasan override penutupan')),
                ('reopen_reason', models.TextField(blank=True, verbose_name='alasan buka kembali')),
                ('version', models.PositiveIntegerField(default=1)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operational_days', to='core.clinic')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='days_closed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='days_created', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='days_opened', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'hari operasional',
                'verbose_name_plural': 'hari operasional',
                'ordering': ('-date',),
                'constraints': [models.UniqueConstraint(fields=('clinic', 'date'), name='uniq_clinic_operational_date')],
            },
        ),
    ]
