# Generated by Django 5.1.15 on 2026-09-20 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitem',
            name='assignment_mode',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('BERSAMA', 'Bersama')], default='INDIVIDUAL', max_length=12),
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Terbuka'), ('IN_PROGRESS', 'Dikerjakan'), ('SUBMITTED', 'Diajukan selesai'), ('REVISION_REQUIRED', 'Perlu revisi'), ('CONFIRMED', 'Dikonfirmasi'), ('CANCELLED', 'Dibatalkan')], default='OPEN', max_length=24)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('revision_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assignments', to='core.actionitem')),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assignments', to=settings.AUTH_USER_MODEL)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_task_assignments', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_task_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'assignment task',
                'verbose_name_plural': 'assignment task',
                'ordering': ('action_item', 'assignee__username'),
            },
        ),
        migrations.CreateModel(
            name='TaskAudienceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience_type', models.CharField(choices=[('USER', 'Satu user'), ('USERS', 'Beberapa user'), ('PIC_FUNCTION', 'Fungsi PIC'), ('ROLE', 'Tier/role cabang'), ('CLINIC', 'Seluruh staf cabang')], max_length=24)),
                ('criteria', models.JSONField(blank=True, default=dict)),
                ('recipients', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audience_snapshot', to='core.actionitem')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_audience_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'snapshot penerima task',
                'verbose_name_plural': 'snapshot penerima task',
            },
        ),
        migrations.CreateModel(
            name='TaskEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('SENT', 'Dikirim'), ('CLAIMED', 'Diambil'), ('SUBMITTED', 'Diajukan selesai'), ('CONFIRMED', 'Dikonfirmasi'), ('REVISION_REQUESTED', 'Diminta revisi'), ('CANCELLED', 'Dibatalkan'), ('COMMENT', 'Komentar')], max_length=24)),
                ('note', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_events', to='core.actionitem')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_events', to=settings.AUTH_USER_MODEL)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.taskassignment')),
            ],
            options={
                'verbose_name': 'event task',
                'verbose_name_plural': 'event task',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='taskassignment',
            constraint=models.UniqueConstraint(fields=('action_item', 'assignee'), name='uniq_task_assignment_recipient'),
        ),
    ]
