# Generated by Django 5.1.15 on 2026-09-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_actionitem_assignment_mode_taskassignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitem',
            name='imported_legacy',
            field=models.BooleanField(default=False, verbose_name='hasil import legacy'),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='legacy_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='waktu selesai asli (legacy)'),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='legacy_source_id',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='ID sumber legacy'),
        ),
    ]
