# Generated by Django 5.1.15 on 2026-09-29 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_actionitem_imported_legacy_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinic",
            name="apj_name",
            field=models.CharField(
                blank=True,
                help_text="Nama lengkap beserta gelar.",
                max_length=160,
                verbose_name="apoteker penanggung jawab (APJ)",
            ),
        ),
        migrations.AddField(
            model_name="clinic",
            name="dpj_name",
            field=models.CharField(
                blank=True,
                help_text="Nama lengkap beserta gelar, mis. dr. Yohanes Widjaja, Sp.DVE.",
                max_length=160,
                verbose_name="dokter penanggung jawab (DPJ)",
            ),
        ),
        migrations.AddField(
            model_name="clinic",
            name="phone",
            field=models.CharField(
                blank=True, max_length=40, verbose_name="nomor HP/WhatsApp"
            ),
        ),
    ]
