# Generated by Django 5.1.15 on 2026-10-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_clinic_profile_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="actionitem",
            name="review_by",
            field=models.CharField(
                choices=[
                    ("DIREKTUR", "Direktur Operasional"),
                    ("DIRUT", "Direktur Utama / Owner"),
                ],
                default="DIREKTUR",
                help_text="Siapa yang memverifikasi. Task yang dikerjakan Direktur Operasional sendiri selalu diperiksa Direktur Utama / Owner (lihat effective_review_by).",
                max_length=10,
                verbose_name="pemeriksa",
            ),
        ),
        migrations.AlterField(
            model_name="taskevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("SENT", "Dikirim"),
                    ("CLAIMED", "Diambil"),
                    ("SUBMITTED", "Diajukan selesai"),
                    ("CONFIRMED", "Dikonfirmasi"),
                    ("REVISION_REQUESTED", "Diminta revisi"),
                    ("CANCELLED", "Dibatalkan"),
                    ("COMMENT", "Komentar"),
                    ("PROGRESS", "Laporan progres"),
                ],
                max_length=24,
            ),
        ),
    ]
