# Generated by Django 5.1.15 on 2026-10-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_pemeriksa_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinic",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="lintang",
            ),
        ),
        migrations.AddField(
            model_name="clinic",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="bujur",
            ),
        ),
        migrations.AddField(
            model_name="clinic",
            name="radius_m",
            field=models.PositiveIntegerField(
                default=150,
                help_text="Jejak dengan lokasi di dalam radius ini berlabel Kuat (tahap 3 paket E).",
                verbose_name="radius klinik (m)",
            ),
        ),
    ]
