# Generated by Django 5.1.15 on 2026-10-07 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_koordinat_cabang'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitem',
            name='blocked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ditandai terhambat'),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='blocked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='blocked_reason',
            field=models.TextField(blank=True, verbose_name='alasan terhambat'),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='proposed_due_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='usulan target baru'),
        ),
        migrations.AlterField(
            model_name='taskevent',
            name='event_type',
            field=models.CharField(choices=[('SENT', 'Dikirim'), ('CLAIMED', 'Diambil'), ('SUBMITTED', 'Diajukan selesai'), ('CONFIRMED', 'Dikonfirmasi'), ('REVISION_REQUESTED', 'Diminta revisi'), ('CANCELLED', 'Dibatalkan'), ('COMMENT', 'Komentar'), ('PROGRESS', 'Laporan progres'), ('KENDALA', 'Kendala'), ('TARGET_DIUBAH', 'Target diubah')], max_length=24),
        ),
    ]
