# Generated by Django 5.1.15 on 2026-10-08 16:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_task_kendala'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='nama')),
                ('active', models.BooleanField(default=True, verbose_name='aktif')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='urutan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'kategori task',
                'verbose_name_plural': 'kategori task',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='rated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='rated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='bintang'),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='rating_auto',
            field=models.BooleanField(default=False, verbose_name='bintang otomatis'),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='rating_note',
            field=models.TextField(blank=True, verbose_name='alasan bintang'),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_items', to='core.taskcategory', verbose_name='kategori'),
        ),
    ]
