# Generated by Django 5.1.15 on 2026-09-30 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0005_clinic_profile_data"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Produk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "omnicare_id",
                    models.PositiveIntegerField(
                        unique=True, verbose_name="ID Omnicare"
                    ),
                ),
                ("nama", models.CharField(max_length=200)),
                ("dosis", models.CharField(blank=True, max_length=60)),
                (
                    "kunci",
                    models.CharField(
                        max_length=260, unique=True, verbose_name="kunci pencocokan"
                    ),
                ),
                (
                    "generik",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="nama generik"
                    ),
                ),
                ("pabrikan", models.CharField(blank=True, max_length=120)),
                ("kategori", models.CharField(blank=True, max_length=80)),
                ("sediaan", models.CharField(blank=True, max_length=60)),
                ("satuan", models.CharField(blank=True, max_length=40)),
                ("harga_modal", models.FloatField(default=0)),
                ("harga_jual", models.FloatField(default=0)),
                (
                    "min_omnicare",
                    models.FloatField(default=0, verbose_name="MIN Omnicare"),
                ),
                (
                    "max_omnicare",
                    models.FloatField(default=0, verbose_name="MAX Omnicare"),
                ),
                (
                    "non_stok",
                    models.BooleanField(
                        default=False, verbose_name="non-stok (racik/jasa)"
                    ),
                ),
                ("aktif", models.BooleanField(default=True)),
                ("diperbarui", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "produk",
                "verbose_name_plural": "produk",
                "ordering": ("nama",),
            },
        ),
        migrations.CreateModel(
            name="Parameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bulan_rata_rata",
                    models.PositiveSmallIntegerField(
                        default=3, verbose_name="jumlah bulan rata-rata"
                    ),
                ),
                (
                    "bulan_buffer",
                    models.FloatField(default=1, verbose_name="bulan buffer"),
                ),
                (
                    "ambang_mendekati",
                    models.FloatField(
                        default=0.25, verbose_name="ambang mendekati buffer (desimal)"
                    ),
                ),
                (
                    "target_bulan",
                    models.FloatField(
                        default=2, verbose_name="target stok setelah order (bulan)"
                    ),
                ),
                (
                    "cadangan_bulan",
                    models.FloatField(
                        default=2, verbose_name="cadangan cabang pengirim (bulan)"
                    ),
                ),
                ("diubah", models.DateTimeField(auto_now=True)),
                (
                    "diubah_oleh",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "parameter stok",
                "verbose_name_plural": "parameter stok",
            },
        ),
        migrations.CreateModel(
            name="ProdukAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kunci", models.CharField(max_length=260, unique=True)),
                (
                    "produk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alias",
                        to="stok.produk",
                    ),
                ),
            ],
            options={
                "verbose_name": "alias produk",
                "verbose_name_plural": "alias produk",
            },
        ),
        migrations.CreateModel(
            name="Unggahan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "jenis",
                    models.CharField(
                        choices=[
                            ("DAFTAR_PRODUK", "Daftar Produk"),
                            ("TINGKAT_PERSEDIAAN", "Tingkat Persediaan"),
                            ("PERGERAKAN", "Ringkasan Pergerakan Stok"),
                        ],
                        max_length=24,
                    ),
                ),
                ("tahun", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("bulan", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "tanggal",
                    models.DateField(
                        blank=True, null=True, verbose_name="tanggal data"
                    ),
                ),
                (
                    "judul",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="judul laporan"
                    ),
                ),
                ("nama_file", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="stok/%Y/%m/")),
                ("jumlah_baris", models.PositiveIntegerField(default=0)),
                ("jumlah_cocok", models.PositiveIntegerField(default=0)),
                ("peringatan", models.JSONField(blank=True, default=list)),
                ("waktu", models.DateTimeField(auto_now_add=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.clinic",
                    ),
                ),
                (
                    "diunggah_oleh",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "unggahan Omnicare",
                "verbose_name_plural": "unggahan Omnicare",
                "ordering": ("-waktu", "-pk"),
            },
        ),
        migrations.CreateModel(
            name="StatusPeriode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tahun", models.PositiveSmallIntegerField()),
                ("bulan", models.PositiveSmallIntegerField()),
                ("lengkap", models.BooleanField(default=False)),
                (
                    "hasil",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="hasil uji"
                    ),
                ),
                (
                    "diduga_hilang",
                    models.JSONField(
                        blank=True, default=list, verbose_name="produk diduga hilang"
                    ),
                ),
                (
                    "selisih_stok",
                    models.JSONField(
                        blank=True,
                        default=list,
                        verbose_name="selisih dengan tingkat persediaan",
                    ),
                ),
                ("jumlah_baris", models.PositiveIntegerField(default=0)),
                ("diperbarui", models.DateTimeField(auto_now=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.clinic",
                    ),
                ),
            ],
            options={
                "verbose_name": "status periode",
                "verbose_name_plural": "status periode",
                "ordering": ("clinic", "-tahun", "-bulan"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("clinic", "tahun", "bulan"), name="uniq_status_periode"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PosisiStok",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tanggal", models.DateField()),
                ("stok", models.FloatField(default=0)),
                ("nilai_modal", models.FloatField(default=0)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.clinic",
                    ),
                ),
                (
                    "produk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posisi",
                        to="stok.produk",
                    ),
                ),
                (
                    "unggahan",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="stok.unggahan",
                    ),
                ),
            ],
            options={
                "verbose_name": "posisi stok",
                "verbose_name_plural": "posisi stok",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("clinic", "produk", "tanggal"), name="uniq_posisi_stok"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PergerakanBulanan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tahun", models.PositiveSmallIntegerField()),
                ("bulan", models.PositiveSmallIntegerField()),
                ("stok_awal", models.FloatField(default=0)),
                ("diterima", models.FloatField(default=0)),
                ("dijual", models.FloatField(default=0)),
                ("dipakai", models.FloatField(default=0)),
                ("fabrikasi", models.FloatField(default=0)),
                ("retur_jual", models.FloatField(default=0)),
                ("retur_beli", models.FloatField(default=0)),
                ("rusak", models.FloatField(default=0)),
                ("mutasi", models.FloatField(default=0)),
                ("penyesuaian", models.FloatField(default=0)),
                ("gabung", models.FloatField(default=0)),
                ("stok_akhir", models.FloatField(default=0)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.clinic",
                    ),
                ),
                (
                    "produk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pergerakan",
                        to="stok.produk",
                    ),
                ),
                (
                    "unggahan",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="stok.unggahan",
                    ),
                ),
            ],
            options={
                "verbose_name": "pergerakan bulanan",
                "verbose_name_plural": "pergerakan bulanan",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("clinic", "produk", "tahun", "bulan"),
                        name="uniq_pergerakan",
                    )
                ],
            },
        ),
    ]
