# Generated by Django 5.1.15 on 2026-09-11 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercapability',
            name='capability',
            field=models.CharField(choices=[('cash.view_amounts', 'Melihat nominal kas'), ('cash.approve', 'Menyetujui/verifikasi kas'), ('patient.view_detail', 'Melihat detail pasien'), ('issue.view_restricted', 'Melihat komplain terbatas'), ('audit.view', 'Membaca audit log'), ('report.export', 'Mengekspor laporan'), ('admin.full_access', 'Admin akses penuh (kas, pasien, komplain terbatas, audit)')], max_length=40),
        ),
    ]
