# Generated by Django 5.1.15 on 2026-09-20 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_usercapability_capability'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercapability',
            name='capability',
            field=models.CharField(choices=[('cash.view_amounts', 'Melihat nominal kas'), ('cash.approve', 'Menyetujui/verifikasi kas'), ('patient.view_detail', 'Melihat detail pasien'), ('issue.view_restricted', 'Melihat komplain terbatas'), ('report.view_confidential', 'Melihat laporan rahasia'), ('suggestion.publish', 'Memublikasikan masukan ke cabang'), ('user.manage', 'Mengelola pengguna'), ('audit.view', 'Membaca audit log'), ('report.export', 'Mengekspor laporan'), ('admin.full_access', 'Admin akses penuh (kas, pasien, komplain terbatas, audit)')], max_length=40),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('STAF', 'Staf operasional'), ('FRONT_DESK', 'Front desk/kasir'), ('PERAWAT', 'Perawat'), ('SUPERVISOR', 'Supervisor'), ('PIC', 'PIC cabang'), ('AOM', 'AOM lintas cabang'), ('ADMIN', 'Admin'), ('OWNER', 'Owner/Manajemen')], max_length=20),
        ),
        migrations.CreateModel(
            name='OrganizationAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='jabatan')),
                ('starts_on', models.DateField(verbose_name='mulai')),
                ('ends_on', models.DateField(blank=True, null=True, verbose_name='selesai')),
                ('active', models.BooleanField(default=True, verbose_name='aktif')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='catatan')),
                ('clinic', models.ForeignKey(blank=True, help_text='Kosongkan untuk jabatan lintas cabang.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_assignments', to='core.clinic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'jabatan organisasi',
                'verbose_name_plural': 'jabatan organisasi',
                'ordering': ('user__username', 'clinic__code', 'title'),
                'constraints': [models.UniqueConstraint(fields=('user', 'clinic', 'title', 'starts_on'), name='uniq_user_clinic_org_assignment')],
            },
        ),
        migrations.CreateModel(
            name='PicAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.CharField(choices=[('SHIFT_COORDINATOR', 'Koordinator shift'), ('CASHIER', 'Kasir'), ('ONLINE', 'Online'), ('CLEANLINESS', 'Kebersihan')], max_length=32)),
                ('starts_on', models.DateField(verbose_name='mulai')),
                ('ends_on', models.DateField(blank=True, null=True, verbose_name='selesai')),
                ('active', models.BooleanField(default=True, verbose_name='aktif')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pic_assignments', to='core.clinic')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pic_assignments_granted', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pic_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'penugasan PIC',
                'verbose_name_plural': 'penugasan PIC',
                'ordering': ('clinic__code', 'function', 'user__username'),
                'constraints': [models.UniqueConstraint(fields=('user', 'clinic', 'function', 'starts_on'), name='uniq_user_clinic_pic_assignment')],
            },
        ),
    ]
