# Generated by Django 5.1.15 on 2026-09-20 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_usercapability_capability_alter_userrole_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('STAF', 'Staf operasional'), ('FRONT_DESK', 'Front desk/kasir'), ('PERAWAT', 'Perawat'), ('APOTEKER', 'Apoteker'), ('ONLINE', 'Online/reservasi'), ('SUPERVISOR', 'Supervisor'), ('PIC', 'PIC cabang'), ('AOM', 'AOM lintas cabang'), ('ADMIN', 'Admin'), ('OWNER', 'Owner/Manajemen')], max_length=20),
        ),
    ]
