# Generated by Django 5.1.15 on 2026-09-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userrole_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picassignment',
            name='function',
            field=models.CharField(choices=[('SHIFT_COORDINATOR', 'Koordinator shift'), ('CASHIER', 'Koordinator kasir'), ('ONLINE', 'Koordinator online'), ('CLEANLINESS', 'Kebersihan')], max_length=32),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('STAF', 'Staf operasional'), ('FRONT_DESK', 'Front desk/kasir'), ('PERAWAT', 'Perawat'), ('APOTEKER', 'Apoteker'), ('ASISTEN_APOTEKER', 'Asisten apoteker'), ('ONLINE', 'Koordinator online'), ('SUPERVISOR', 'Koordinator shift'), ('PIC', 'PIC cabang'), ('AOM', 'AOM lintas cabang'), ('ADMIN', 'Admin'), ('OWNER', 'Owner/Manajemen')], max_length=20),
        ),
    ]
