# Generated by Django 5.1.15 on 2026-09-29 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_picassignment_function_alter_userrole_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="picassignment",
            name="function",
            field=models.CharField(
                choices=[
                    ("SHIFT_COORDINATOR", "Koordinator Shift"),
                    ("CASHIER", "PIC Kasir"),
                    ("ONLINE", "Koordinator Layanan Daring"),
                    ("CLEANLINESS", "PJ Kebersihan dan Sterilitas"),
                    ("PHARMACY", "PIC Apotek"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="role",
            field=models.CharField(
                choices=[
                    ("STAF", "Staf operasional"),
                    ("FRONT_DESK", "Front desk/kasir"),
                    ("PERAWAT", "Perawat"),
                    ("APOTEKER", "Apoteker"),
                    ("ASISTEN_APOTEKER", "Asisten apoteker"),
                    ("ONLINE", "Koordinator layanan daring"),
                    ("SUPERVISOR", "Koordinator shift"),
                    ("PIC", "PIC cabang"),
                    ("AOM", "Direktur Operasional"),
                    ("ADMIN", "Admin"),
                    ("OWNER", "Owner/Manajemen"),
                ],
                max_length=20,
            ),
        ),
    ]
