# Generated by Django 5.1.15 on 2026-09-29 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_director_labels"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userrole",
            name="role",
            field=models.CharField(
                choices=[
                    ("STAF", "Staf operasional"),
                    ("FRONT_DESK", "Front desk/kasir"),
                    ("PERAWAT", "Perawat"),
                    ("APOTEKER", "Apoteker"),
                    ("ASISTEN_APOTEKER", "Asisten apoteker"),
                    ("ONLINE", "Koordinator layanan daring"),
                    ("SUPERVISOR", "Koordinator shift"),
                    ("PIC", "PIC cabang"),
                    ("AOM", "Direktur Operasional"),
                    ("ADMIN", "Admin"),
                    ("OWNER", "Owner / Direktur Utama"),
                ],
                max_length=20,
            ),
        ),
    ]
