# Generated by Django 5.1.15 on 2026-10-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_owner_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercapability",
            name="capability",
            field=models.CharField(
                choices=[
                    ("cash.view_amounts", "Melihat nominal kas"),
                    ("cash.approve", "Menyetujui/verifikasi kas"),
                    ("patient.view_detail", "Melihat detail pasien"),
                    ("issue.view_restricted", "Melihat komplain terbatas"),
                    ("report.view_confidential", "Melihat laporan rahasia"),
                    ("suggestion.publish", "Memublikasikan masukan ke cabang"),
                    ("user.manage", "Mengelola pengguna"),
                    ("audit.view", "Membaca audit log"),
                    ("report.export", "Mengekspor laporan"),
                    (
                        "tally.correct",
                        "Mengoreksi tally perawat (cabang yang dapat diakses)",
                    ),
                    (
                        "admin.full_access",
                        "Admin akses penuh (kas, pasien, komplain terbatas, audit)",
                    ),
                ],
                max_length=40,
            ),
        ),
    ]
