# Generated by Django 5.1.15 on 2026-09-10 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('queueing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NurseRosterEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='posisi antrean giliran')),
                ('availability', models.CharField(choices=[('TERSEDIA', 'Tersedia'), ('ISTIRAHAT', 'Istirahat'), ('OFF_DUTY', 'Pulang/off')], default='TERSEDIA', max_length=10)),
                ('turns_taken', models.PositiveIntegerField(default=0, verbose_name='giliran terpakai')),
                ('note', models.CharField(blank=True, max_length=200)),
                ('version', models.PositiveIntegerField(default=1)),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roster_entries', to=settings.AUTH_USER_MODEL)),
                ('operational_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_roster', to='core.operationalday')),
            ],
            options={
                'verbose_name': 'roster perawat',
                'verbose_name_plural': 'roster perawat',
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProcedureCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, verbose_name='kode')),
                ('name', models.CharField(max_length=120, verbose_name='nama kategori tindakan')),
                ('commissioned', models.BooleanField(default=True, verbose_name='berkomisi')),
                ('active', models.BooleanField(default=True, verbose_name='aktif')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedure_categories', to='core.clinic')),
            ],
            options={
                'verbose_name': 'kategori tindakan',
                'verbose_name_plural': 'kategori tindakan',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ProcedureAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DITUGASKAN', 'Ditugaskan'), ('DIMULAI', 'Dimulai'), ('SELESAI', 'Selesai'), ('BATAL', 'Batal')], default='DITUGASKAN', max_length=12)),
                ('note', models.CharField(blank=True, max_length=250)),
                ('override_reason', models.TextField(blank=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedures_assigned', to=settings.AUTH_USER_MODEL)),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procedures', to=settings.AUTH_USER_MODEL)),
                ('operational_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='core.operationalday')),
                ('queue_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedures', to='queueing.queueentry')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nurses.procedurecategory')),
            ],
            options={
                'verbose_name': 'tindakan berkomisi',
                'verbose_name_plural': 'tindakan berkomisi',
                'ordering': ('-assigned_at',),
            },
        ),
        migrations.CreateModel(
            name='NurseEligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibilities', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligible_nurses', to='nurses.procedurecategory')),
            ],
            options={
                'verbose_name': 'eligibility perawat',
                'verbose_name_plural': 'eligibility perawat',
            },
        ),
        migrations.CreateModel(
            name='CommissionTurnEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ROSTER_DIBUAT', 'Roster dibuat'), ('TINDAKAN_DITUGASKAN', 'Tindakan ditugaskan'), ('TINDAKAN_DIMULAI', 'Tindakan dimulai'), ('TINDAKAN_SELESAI', 'Tindakan selesai (giliran terpakai)'), ('TINDAKAN_BATAL', 'Tindakan batal'), ('SKIP', 'Skip sementara'), ('OVERRIDE', 'Override supervisor'), ('TIDAK_ELIGIBLE', 'Dilewati: tidak eligible'), ('AVAILABILITY_BERUBAH', 'Ketersediaan berubah')], max_length=22)),
                ('reason', models.TextField(blank=True)),
                ('position_before', models.PositiveIntegerField(blank=True, null=True)),
                ('position_after', models.PositiveIntegerField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turn_events_created', to=settings.AUTH_USER_MODEL)),
                ('nurse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turn_events', to=settings.AUTH_USER_MODEL)),
                ('operational_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turn_events', to='core.operationalday')),
                ('queue_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turn_events', to='queueing.queueentry')),
                ('roster_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turn_events', to='nurses.nurserosterentry')),
                ('procedure_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nurses.procedurecategory')),
            ],
            options={
                'verbose_name': 'event giliran',
                'verbose_name_plural': 'event giliran',
                'ordering': ('-occurred_at', '-id'),
            },
        ),
        migrations.AddConstraint(
            model_name='nurserosterentry',
            constraint=models.UniqueConstraint(fields=('operational_day', 'nurse'), name='uniq_roster_day_nurse'),
        ),
        migrations.AddConstraint(
            model_name='procedurecategory',
            constraint=models.UniqueConstraint(fields=('clinic', 'code'), name='uniq_procedure_code'),
        ),
        migrations.AddConstraint(
            model_name='nurseeligibility',
            constraint=models.UniqueConstraint(fields=('nurse', 'category'), name='uniq_nurse_category'),
        ),
    ]
