# Generated by Django 5.1.15 on 2026-09-20 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_actionitem_assignment_mode_taskassignment_and_more'),
        ('nurses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NurseActionTally',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rm_number', models.CharField(max_length=32, verbose_name='nomor RM')),
                ('patient_name', models.CharField(max_length=120, verbose_name='nama pasien')),
                ('action_name', models.CharField(max_length=160, verbose_name='tindakan')),
                ('tally', models.PositiveIntegerField(default=1, verbose_name='jumlah')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nurse_tallies_entered', to=settings.AUTH_USER_MODEL)),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nurse_tallies', to=settings.AUTH_USER_MODEL)),
                ('operational_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_tallies', to='core.operationalday')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
