# Generated by Django 5.1.15 on 2026-09-29 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nurses", "0002_nurseactiontally"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nurserosterentry",
            name="availability",
            field=models.CharField(
                choices=[
                    ("TERSEDIA", "Tersedia"),
                    ("MENANGANI", "Sedang menangani"),
                    ("ISTIRAHAT", "Istirahat"),
                    ("OFF_DUTY", "Pulang/off"),
                ],
                default="TERSEDIA",
                max_length=10,
            ),
        ),
    ]
