# Generated by Django 5.1.15 on 2026-09-29 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nurses", "0003_availability_menangani"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commissionturnevent",
            name="action",
            field=models.CharField(
                choices=[
                    ("ROSTER_DIBUAT", "Roster dibuat"),
                    ("TINDAKAN_DITUGASKAN", "Tindakan ditugaskan"),
                    ("TINDAKAN_DIMULAI", "Tindakan dimulai"),
                    ("TINDAKAN_SELESAI", "Tindakan selesai (giliran terpakai)"),
                    ("TINDAKAN_BATAL", "Tindakan batal"),
                    ("SKIP", "Skip sementara"),
                    ("OVERRIDE", "Override supervisor"),
                    ("TIDAK_ELIGIBLE", "Dilewati: tidak eligible"),
                    ("AVAILABILITY_BERUBAH", "Ketersediaan berubah"),
                    ("PASIEN_DISERAHKAN", "Pasien diserahkan"),
                    ("URUTAN_DIUBAH", "Urutan papan diubah"),
                ],
                max_length=22,
            ),
        ),
    ]
