# Generated by Django 5.1.15 on 2026-10-03 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nurses", "0004_turn_actions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="nurseactiontally",
            name="corrected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nurseactiontally",
            name="corrected_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="nurseactiontally",
            name="correction_reason",
            field=models.CharField(
                blank=True, max_length=250, verbose_name="alasan koreksi"
            ),
        ),
    ]
