# Generated by Django 5.1.15 on 2026-10-07 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurses', '0005_tally_correction'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurseactiontally',
            name='susulan',
            field=models.BooleanField(default=False, verbose_name='tally susulan'),
        ),
        migrations.AddField(
            model_name='nurseactiontally',
            name='susulan_reason',
            field=models.CharField(blank=True, max_length=250, verbose_name='alasan susulan'),
        ),
        migrations.AlterField(
            model_name='nurseactiontally',
            name='action_name',
            field=models.CharField(blank=True, max_length=160, verbose_name='tindakan'),
        ),
        migrations.AlterField(
            model_name='nurseactiontally',
            name='patient_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='nama pasien'),
        ),
        migrations.AlterField(
            model_name='nurseactiontally',
            name='rm_number',
            field=models.CharField(blank=True, max_length=32, verbose_name='nomor RM'),
        ),
    ]
