# Generated by Django 5.1.15 on 2026-09-10 17:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('OPENING', 'Kas awal'), ('CLOSING', 'Kas akhir')], max_length=10, verbose_name='jenis')),
                ('shift', models.CharField(blank=True, max_length=40, verbose_name='shift')),
                ('expected_total', models.BigIntegerField(default=0, verbose_name='jumlah diharapkan (Rp)')),
                ('actual_total', models.BigIntegerField(default=0, verbose_name='jumlah aktual (Rp)')),
                ('change_fund_total', models.BigIntegerField(default=0, verbose_name='uang kembalian (Rp)')),
                ('other_funds_total', models.BigIntegerField(default=0, verbose_name='dana kas lain (Rp)')),
                ('variance', models.BigIntegerField(default=0, verbose_name='selisih (Rp)')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('MENUNGGU_VERIFIKASI', 'Menunggu verifikasi'), ('SESUAI', 'Sesuai'), ('SELISIH', 'Selisih'), ('DISETUJUI_DENGAN_CATATAN', 'Disetujui dengan catatan')], default='DRAFT', max_length=26)),
                ('note', models.TextField(blank=True, verbose_name='catatan')),
                ('counted_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('correction_reason', models.TextField(blank=True, verbose_name='alasan koreksi')),
                ('version', models.PositiveIntegerField(default=1)),
                ('corrected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_corrections', to=settings.AUTH_USER_MODEL)),
                ('counted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_counts', to=settings.AUTH_USER_MODEL)),
                ('operational_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_sessions', to='core.operationalday')),
            ],
            options={
                'verbose_name': 'sesi kas',
                'verbose_name_plural': 'sesi kas',
                'ordering': ('operational_day', 'session_type'),
            },
        ),
        migrations.CreateModel(
            name='CashDenominationCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denomination', models.PositiveIntegerField(verbose_name='pecahan (Rp)')),
                ('quantity', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='jumlah')),
                ('cash_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denominations', to='cash.cashsession')),
            ],
            options={
                'verbose_name': 'rincian pecahan',
                'verbose_name_plural': 'rincian pecahan',
                'ordering': ('-denomination',),
            },
        ),
        migrations.CreateModel(
            name='CashVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recounted_total', models.BigIntegerField(blank=True, null=True, verbose_name='total hitung ulang (Rp)')),
                ('result', models.CharField(choices=[('SESUAI', 'Sesuai'), ('SELISIH', 'Selisih'), ('DISETUJUI_DENGAN_CATATAN', 'Disetujui dengan catatan'), ('DITOLAK', 'Ditolak / hitung ulang')], max_length=26)),
                ('note', models.TextField(blank=True, verbose_name='catatan')),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('cash_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='cash.cashsession')),
                ('verifier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'verifikasi kas',
                'verbose_name_plural': 'verifikasi kas',
                'ordering': ('-verified_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='cashsession',
            constraint=models.UniqueConstraint(fields=('operational_day', 'session_type', 'shift'), name='uniq_cash_day_type_shift'),
        ),
        migrations.AddConstraint(
            model_name='cashdenominationcount',
            constraint=models.UniqueConstraint(fields=('cash_session', 'denomination'), name='uniq_cash_denomination'),
        ),
        migrations.AddConstraint(
            model_name='cashdenominationcount',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='cash_quantity_non_negative'),
        ),
    ]
