# Generated by Django 5.1.15 on 2026-10-05 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cash", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashsession",
            name="cash_in_total",
            field=models.BigIntegerField(
                default=0, verbose_name="tunai masuk hari itu (Rp)"
            ),
        ),
        migrations.AddField(
            model_name="cashsession",
            name="cash_out_total",
            field=models.BigIntegerField(
                default=0, verbose_name="tunai keluar dari laci (Rp)"
            ),
        ),
        migrations.AddField(
            model_name="cashsession",
            name="expected_basis",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="dasar angka diharapkan"
            ),
        ),
    ]
