# Generated by Django 5.1.15 on 2026-09-20 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_actionitem_assignment_mode_taskassignment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Laporan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility', models.CharField(choices=[('CABANG', 'Terlihat satu cabang'), ('RAHASIA_AOM', 'Rahasia — hanya pelapor dan AOM')], db_index=True, max_length=20, verbose_name='visibilitas')),
                ('status', models.CharField(choices=[('OPEN', 'Baru'), ('UNDER_REVIEW', 'Ditinjau'), ('RESOLVED', 'Selesai'), ('CLOSED', 'Ditutup'), ('ARCHIVED', 'Diarsipkan')], db_index=True, default='OPEN', max_length=20)),
                ('title', models.CharField(max_length=200, verbose_name='ringkasan')),
                ('description', models.TextField(blank=True, verbose_name='uraian')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('archive_reason', models.TextField(blank=True, verbose_name='alasan arsip')),
                ('version', models.PositiveIntegerField(default=1)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laporan_diarsipkan', to=settings.AUTH_USER_MODEL)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laporan_set', to='core.clinic')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laporan_dibuat', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'laporan',
                'verbose_name_plural': 'laporan',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='LaporanUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(blank=True, max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laporan_updates', to=settings.AUTH_USER_MODEL)),
                ('laporan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='reports.laporan')),
            ],
            options={
                'verbose_name': 'riwayat laporan',
                'verbose_name_plural': 'riwayat laporan',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Masukan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='ringkasan')),
                ('description', models.TextField(blank=True, verbose_name='uraian')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('archive_reason', models.TextField(blank=True, verbose_name='alasan arsip')),
                ('version', models.PositiveIntegerField(default=1)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='masukan_diarsipkan', to=settings.AUTH_USER_MODEL)),
                ('clinic', models.ForeignKey(help_text='Cabang pengirim saat masukan dibuat (bukan target publikasi).', on_delete=django.db.models.deletion.CASCADE, related_name='masukan_set', to='core.clinic')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='masukan_dibuat', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'masukan',
                'verbose_name_plural': 'masukan',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MasukanPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('title_snapshot', models.CharField(max_length=200)),
                ('description_snapshot', models.TextField(blank=True)),
                ('source_version', models.PositiveIntegerField(help_text='Versi Masukan.version pada saat publikasi (histori tidak berubah).')),
                ('clinics', models.ManyToManyField(related_name='masukan_publications', to='core.clinic', verbose_name='cabang tujuan')),
                ('masukan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='reports.masukan')),
                ('published_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='masukan_dipublikasikan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'publikasi masukan',
                'verbose_name_plural': 'publikasi masukan',
                'ordering': ('-published_at',),
            },
        ),
        migrations.AddIndex(
            model_name='laporan',
            index=models.Index(fields=['clinic', 'visibility', 'status'], name='reports_lap_clinic__f08783_idx'),
        ),
    ]
