# Generated by Django 5.1.15 on 2026-09-29 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="laporan",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("CABANG", "Terlihat satu cabang"),
                    ("RAHASIA_AOM", "Rahasia — hanya pelapor dan Direktur Operasional"),
                ],
                db_index=True,
                max_length=20,
                verbose_name="visibilitas",
            ),
        ),
    ]
