# Generated by Django 5.1.15 on 2026-10-03 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_clinic_profile_data"),
        ("direktur", "0005_keputusan_rapat_bersama"),
        ("reports", "0002_director_label"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InboxTriage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(max_length=24, verbose_name="jenis sumber"),
                ),
                ("source_id", models.PositiveIntegerField(verbose_name="id sumber")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("TUGASKAN", "Diputuskan dan ditugaskan"),
                            ("TERUSKAN", "Diteruskan, dipantau"),
                            ("RAPAT", "Dibawa ke rapat bersama"),
                            ("TIDAK", "Tidak ditindaklanjuti"),
                        ],
                        max_length=12,
                        verbose_name="hasil pilah",
                    ),
                ),
                (
                    "forwarded_to",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "DIRUT",
                                "Direktur Utama / Owner (strategis, SP/pemberhentian)",
                            ),
                            ("APOTEKER", "Apoteker (apotek, stok, harga obat)"),
                            ("KEUANGAN", "Keuangan (di atas Rp1 juta)"),
                            ("MEDIS", "Penanggung jawab medis"),
                            ("OMNICARE", "Omnicare"),
                            ("LAINNYA", "Lainnya"),
                        ],
                        max_length=12,
                        verbose_name="diteruskan ke",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="catatan")),
                (
                    "triaged_at",
                    models.DateTimeField(auto_now=True, verbose_name="dipilah pada"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "decision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inbox_triages",
                        to="direktur.decision",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inbox_triages",
                        to="core.actionitem",
                    ),
                ),
                (
                    "triaged_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inbox_triages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "pilah inbox",
                "verbose_name_plural": "pilah inbox",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source_type", "source_id"),
                        name="uniq_inbox_triage_source",
                    )
                ],
            },
        ),
    ]
