# Generated by Django 5.1.15 on 2026-10-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0003_pilah_inbox"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inboxtriage",
            name="action",
            field=models.CharField(
                choices=[
                    ("TUGASKAN", "Diputuskan dan ditugaskan"),
                    ("TERUSKAN", "Diteruskan, dipantau"),
                    ("RAPAT", "Dibawa ke rapat bersama"),
                    ("KEBIJAKAN", "Dijadikan kebijakan"),
                    ("TIDAK", "Tidak ditindaklanjuti"),
                ],
                max_length=12,
                verbose_name="hasil pilah",
            ),
        ),
    ]
