# Generated by Django 5.1.15 on 2026-10-07 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_triage_kebijakan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MasukanTanggapan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(verbose_name='tanggapan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('masukan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tanggapan', to='reports.masukan')),
            ],
            options={
                'verbose_name': 'tanggapan masukan',
                'verbose_name_plural': 'tanggapan masukan',
                'ordering': ('created_at', 'id'),
            },
        ),
    ]
