# Generated by Django 5.1.15 on 2026-09-26 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nama batch')),
                ('source_label', models.CharField(blank=True, max_length=120, verbose_name='label sumber')),
                ('exported_at', models.DateTimeField(blank=True, null=True, verbose_name='waktu ekspor sumber')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='waktu import')),
                ('manifest_checksum', models.CharField(blank=True, max_length=140, verbose_name='checksum manifest ekspor')),
                ('notes', models.TextField(blank=True, help_text='Keputusan eksplisit saat rehearsal, mis. aturan cabang default, jumlah exception, dan hasil rekonsiliasi.', verbose_name='catatan')),
            ],
            options={
                'verbose_name': 'batch import legacy AOM',
                'verbose_name_plural': 'batch import legacy AOM',
                'ordering': ('-imported_at',),
            },
        ),
        migrations.CreateModel(
            name='LegacyActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150, unique=True, verbose_name='label aktor lama')),
                ('mapped_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_actor_labels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'aktor legacy AOM',
                'verbose_name_plural': 'aktor legacy AOM',
                'ordering': ('label',),
            },
        ),
        migrations.CreateModel(
            name='LegacyIdMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_model', models.CharField(max_length=60, verbose_name='model sumber')),
                ('legacy_id', models.CharField(max_length=64, verbose_name='ID legacy')),
                ('target_model', models.CharField(max_length=60, verbose_name='model target')),
                ('target_id', models.PositiveIntegerField(verbose_name='ID target')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_maps', to='aom_migration.legacyimportbatch')),
            ],
            options={
                'verbose_name': 'pemetaan ID legacy',
                'verbose_name_plural': 'pemetaan ID legacy',
                'indexes': [models.Index(fields=['source_model', 'legacy_id'], name='aom_migrati_source__5a1f81_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_model', 'legacy_id', 'target_model'), name='uniq_legacy_id_map')],
            },
        ),
        migrations.CreateModel(
            name='LegacyArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_model', models.CharField(max_length=60, verbose_name='model sumber')),
                ('legacy_id', models.CharField(max_length=64, verbose_name='ID legacy')),
                ('payload', models.JSONField(default=dict, verbose_name='payload asli')),
                ('checksum', models.CharField(blank=True, max_length=140, verbose_name='checksum record')),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archives', to='aom_migration.legacyimportbatch')),
            ],
            options={
                'verbose_name': 'arsip histori legacy AOM',
                'verbose_name_plural': 'arsip histori legacy AOM',
                'ordering': ('source_model', 'legacy_id'),
                'indexes': [models.Index(fields=['source_model', 'legacy_id'], name='aom_migrati_source__f5e12c_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_model', 'legacy_id'), name='uniq_legacy_archive')],
            },
        ),
    ]
