# Generated by Django 5.1.15 on 2026-09-10 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_no', models.PositiveIntegerField(verbose_name='nomor antrean')),
                ('patient_ref', models.CharField(blank=True, max_length=40, verbose_name='ID pasien internal')),
                ('display_name', models.CharField(max_length=120, verbose_name='nama tampilan')),
                ('alias', models.CharField(blank=True, max_length=20, verbose_name='inisial/alias')),
                ('appointment_at', models.DateTimeField(blank=True, null=True, verbose_name='waktu appointment')),
                ('arrived_at', models.DateTimeField(blank=True, null=True, verbose_name='waktu kedatangan')),
                ('visit_type', models.CharField(choices=[('KONSULTASI', 'Konsultasi'), ('TINDAKAN', 'Tindakan'), ('KONTROL', 'Kontrol'), ('LAINNYA', 'Lainnya')], default='KONSULTASI', max_length=12)),
                ('payment_status', models.CharField(choices=[('BELUM_PERLU', 'Belum perlu'), ('BELUM_BAYAR', 'Belum bayar'), ('SUDAH_BAYAR', 'Sudah bayar'), ('DIBEBASKAN', 'Dibebaskan'), ('REFUND', 'Refund')], default='BELUM_BAYAR', max_length=12, verbose_name='status pembayaran konsultasi')),
                ('payment_ref', models.CharField(blank=True, max_length=60, verbose_name='referensi pembayaran internal')),
                ('queue_status', models.CharField(choices=[('DIPESAN', 'Dipesan'), ('CHECK_IN', 'Check-in'), ('MENUNGGU', 'Menunggu'), ('DIPANGGIL', 'Dipanggil'), ('DILAYANI', 'Dilayani'), ('SELESAI', 'Selesai'), ('BATAL', 'Batal'), ('NO_SHOW', 'No-show')], default='DIPESAN', max_length=10)),
                ('position', models.PositiveIntegerField(default=0, verbose_name='urutan tampil')),
                ('priority_flag', models.BooleanField(default=False, verbose_name='prioritas disetujui')),
                ('priority_reason', models.CharField(blank=True, max_length=200)),
                ('note', models.CharField(blank=True, max_length=250, verbose_name='catatan operasional')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_created', to=settings.AUTH_USER_MODEL)),
                ('operational_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='core.operationalday')),
            ],
            options={
                'verbose_name': 'entri antrean',
                'verbose_name_plural': 'entri antrean',
                'ordering': ('position', 'queue_no'),
            },
        ),
        migrations.CreateModel(
            name='PaymentStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('BELUM_PERLU', 'Belum perlu'), ('BELUM_BAYAR', 'Belum bayar'), ('SUDAH_BAYAR', 'Sudah bayar'), ('DIBEBASKAN', 'Dibebaskan'), ('REFUND', 'Refund')], max_length=12)),
                ('to_status', models.CharField(choices=[('BELUM_PERLU', 'Belum perlu'), ('BELUM_BAYAR', 'Belum bayar'), ('SUDAH_BAYAR', 'Sudah bayar'), ('DIBEBASKAN', 'Dibebaskan'), ('REFUND', 'Refund')], max_length=12)),
                ('reason', models.CharField(blank=True, max_length=250)),
                ('payment_ref', models.CharField(blank=True, max_length=60)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_events', to=settings.AUTH_USER_MODEL)),
                ('queue_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_events', to='queueing.queueentry')),
            ],
            options={
                'verbose_name': 'event pembayaran',
                'verbose_name_plural': 'event pembayaran',
                'ordering': ('-occurred_at',),
            },
        ),
        migrations.CreateModel(
            name='QueueStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=10)),
                ('to_status', models.CharField(max_length=10)),
                ('reason', models.CharField(blank=True, max_length=250)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_status_events', to=settings.AUTH_USER_MODEL)),
                ('queue_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='queueing.queueentry')),
            ],
            options={
                'ordering': ('-occurred_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='queueentry',
            constraint=models.UniqueConstraint(fields=('operational_day', 'queue_no'), name='uniq_queue_day_number'),
        ),
    ]
