# Generated by Django 5.1.15 on 2026-09-10 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='tanggal')),
                ('break_type', models.CharField(choices=[('ISTIRAHAT', 'Istirahat'), ('MAKAN', 'Makan'), ('IBADAH', 'Ibadah'), ('LAINNYA', 'Lainnya')], max_length=10, verbose_name='jenis')),
                ('start_at', models.DateTimeField(verbose_name='mulai')),
                ('end_at', models.DateTimeField(verbose_name='selesai')),
                ('location_note', models.CharField(blank=True, max_length=200, verbose_name='lokasi/catatan')),
                ('status', models.CharField(choices=[('DIJADWALKAN', 'Dijadwalkan'), ('BERJALAN', 'Berjalan'), ('SELESAI', 'Selesai'), ('BATAL', 'Batal')], default='DIJADWALKAN', max_length=12)),
                ('staffing_override_reason', models.TextField(blank=True, verbose_name='alasan override minimum staf')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='core.clinic')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breaks_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='break_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'jadwal istirahat',
                'verbose_name_plural': 'jadwal istirahat',
                'ordering': ('date', 'start_at'),
                'indexes': [models.Index(fields=['date', 'user'], name='breaks_brea_date_d9b933_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_at__gt', models.F('start_at'))), name='break_end_after_start')],
            },
        ),
    ]
