# Generated by Django 5.1.15 on 2026-09-10 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_label', models.CharField(blank=True, max_length=150)),
                ('action', models.CharField(choices=[('LOGIN_SUCCESS', 'Login berhasil'), ('LOGIN_FAILED', 'Login gagal'), ('LOGOUT', 'Logout'), ('PASSWORD_CHANGED', 'Password diubah'), ('CREATE', 'Membuat'), ('UPDATE', 'Mengubah'), ('VERIFY', 'Memverifikasi'), ('APPROVE', 'Menyetujui'), ('CANCEL', 'Membatalkan'), ('CLOSE', 'Menutup'), ('REOPEN', 'Membuka kembali'), ('OVERRIDE', 'Override'), ('EXPORT', 'Ekspor data'), ('VIEW_RESTRICTED', 'Akses catatan terbatas'), ('DOWNLOAD_ATTACHMENT', 'Unduh lampiran'), ('PERMISSION_CHANGED', 'Perubahan peran/izin'), ('CONFIG_CHANGED', 'Perubahan konfigurasi')], db_index=True, max_length=32)),
                ('entity_type', models.CharField(db_index=True, max_length=60)),
                ('entity_id', models.CharField(blank=True, db_index=True, max_length=40)),
                ('entity_label', models.CharField(blank=True, max_length=200)),
                ('before_json', models.JSONField(blank=True, null=True)),
                ('after_json', models.JSONField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=40)),
                ('session_key', models.CharField(blank=True, max_length=60)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'audit event',
                'verbose_name_plural': 'audit event',
                'ordering': ('-occurred_at', '-id'),
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='audit_audit_entity__0bff9a_idx')],
            },
        ),
    ]
