# Generated by Django 5.1.15 on 2026-09-20 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'Login berhasil'), ('LOGIN_FAILED', 'Login gagal'), ('LOGOUT', 'Logout'), ('PASSWORD_CHANGED', 'Password diubah'), ('CREATE', 'Membuat'), ('UPDATE', 'Mengubah'), ('CORRECTION', 'Koreksi setelah dicek'), ('VERIFY', 'Memverifikasi'), ('APPROVE', 'Menyetujui'), ('CANCEL', 'Membatalkan'), ('CLOSE', 'Menutup'), ('REOPEN', 'Membuka kembali'), ('OVERRIDE', 'Override'), ('EXPORT', 'Ekspor data'), ('VIEW_RESTRICTED', 'Akses catatan terbatas'), ('DOWNLOAD_ATTACHMENT', 'Unduh lampiran'), ('PERMISSION_CHANGED', 'Perubahan peran/izin'), ('CONFIG_CHANGED', 'Perubahan konfigurasi')], db_index=True, max_length=32),
        ),
    ]
