# Generated by Django 5.1.15 on 2026-09-27 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0003_actionitem_imported_legacy_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.SlugField(max_length=60, unique=True, verbose_name="kode"),
                ),
                (
                    "cadence",
                    models.CharField(
                        choices=[
                            ("HARIAN", "Harian"),
                            ("MINGGUAN", "Mingguan"),
                            ("BULANAN", "Bulanan"),
                        ],
                        max_length=10,
                        verbose_name="siklus",
                    ),
                ),
                ("number", models.PositiveSmallIntegerField(verbose_name="nomor")),
                ("title", models.CharField(max_length=120, verbose_name="cek")),
                ("description", models.TextField(verbose_name="yang dilihat")),
                (
                    "source_label",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="bahan dari"
                    ),
                ),
                (
                    "pic_function",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SHIFT_COORDINATOR", "Koordinator shift"),
                            ("CASHIER", "Koordinator kasir"),
                            ("ONLINE", "Koordinator online"),
                            ("CLEANLINESS", "Kebersihan"),
                        ],
                        default="",
                        help_text="Penerima bawaan task temuan. Kosong berarti dipilih manual saat mencatat temuan.",
                        max_length=32,
                        verbose_name="fungsi PIC tindak lanjut",
                    ),
                ),
                (
                    "clinic_codes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Kosong berarti berlaku di semua cabang, mis. ["citraland"].',
                        verbose_name="berlaku untuk kode cabang",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="aktif")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="urutan"),
                ),
            ],
            options={
                "verbose_name": "butir checklist Direktur",
                "verbose_name_plural": "butir checklist Direktur",
                "ordering": ("cadence", "sort_order", "number"),
            },
        ),
        migrations.CreateModel(
            name="AuditPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=300, verbose_name="yang dicek")),
                (
                    "evidence",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="bukti yang dilihat"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="urutan"),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points",
                        to="direktur.audititem",
                    ),
                ),
            ],
            options={
                "verbose_name": "rincian pemeriksaan",
                "verbose_name_plural": "rincian pemeriksaan",
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.CreateModel(
            name="DirectorNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField(verbose_name="isi")),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Ditulis langsung"),
                            ("PASTE_WA", "Tempelan WhatsApp"),
                        ],
                        default="MANUAL",
                        max_length=10,
                        verbose_name="sumber",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("converted_at", models.DateTimeField(blank=True, null=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="director_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        blank=True,
                        help_text="Kosong untuk catatan lintas cabang.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="director_notes",
                        to="core.clinic",
                    ),
                ),
                (
                    "converted_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_notes",
                        to="core.actionitem",
                        verbose_name="dijadikan task",
                    ),
                ),
            ],
            options={
                "verbose_name": "catatan Direktur",
                "verbose_name_plural": "catatan Direktur",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="AuditCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateField(verbose_name="awal periode")),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("SESUAI", "Sesuai"),
                            ("TEMUAN", "Ada temuan"),
                            ("TIDAK_BERLAKU", "Tidak berlaku"),
                        ],
                        max_length=16,
                        verbose_name="hasil",
                    ),
                ),
                (
                    "direct",
                    models.BooleanField(
                        default=False,
                        help_text="Diperiksa sendiri di lapangan, bukan dari laporan PIC.",
                        verbose_name="dicek langsung",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="catatan")),
                (
                    "item_snapshot",
                    models.JSONField(default=dict, verbose_name="snapshot butir"),
                ),
                (
                    "checked_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="dicek pada"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "checked_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="director_checks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="director_checks",
                        to="core.clinic",
                    ),
                ),
                (
                    "finding",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="director_checks",
                        to="core.actionitem",
                        verbose_name="task temuan",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="checks",
                        to="direktur.audititem",
                    ),
                ),
            ],
            options={
                "verbose_name": "cek Direktur",
                "verbose_name_plural": "cek Direktur",
                "ordering": ("-period_start", "item__sort_order"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("item", "clinic", "period_start"),
                        name="uniq_director_check_period",
                    )
                ],
            },
        ),
    ]
