# Generated by Django 5.1.15 on 2026-09-28 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_actionitem_imported_legacy_and_more"),
        ("direktur", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Decision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Mis. KP-188.",
                        max_length=30,
                        verbose_name="nomor rujukan",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="perkara")),
                (
                    "background",
                    models.TextField(blank=True, verbose_name="latar / pertanyaan"),
                ),
                (
                    "decider",
                    models.CharField(
                        choices=[
                            ("OWNER", "Owner"),
                            ("DIRUT", "Direktur Utama"),
                            ("DIREKTUR_OPERASIONAL", "Direktur Operasional"),
                            ("PJ_PELAYANAN", "Penanggung Jawab Pelayanan"),
                            ("LAINNYA", "Lainnya"),
                        ],
                        max_length=24,
                        verbose_name="diputuskan oleh",
                    ),
                ),
                (
                    "needed_by",
                    models.DateField(
                        blank=True, null=True, verbose_name="perlu diputuskan sebelum"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("MENUNGGU", "Menunggu keputusan"),
                            ("DITETAPKAN", "Ditetapkan"),
                            ("DIBATALKAN", "Dibatalkan"),
                        ],
                        default="MENUNGGU",
                        max_length=12,
                    ),
                ),
                (
                    "decision_text",
                    models.TextField(blank=True, verbose_name="isi keputusan"),
                ),
                (
                    "is_policy",
                    models.BooleanField(
                        default=False,
                        help_text="Keputusan ini menjadi aturan yang berlaku bagi staf.",
                        verbose_name="kebijakan berlaku",
                    ),
                ),
                (
                    "decided_on",
                    models.DateField(
                        blank=True, null=True, verbose_name="tanggal ditetapkan"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        blank=True,
                        help_text="Kosong untuk keputusan lintas cabang.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="director_decisions",
                        to="core.clinic",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="director_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "keputusan",
                "verbose_name_plural": "keputusan",
                "ordering": ("status", "needed_by", "-created_at"),
            },
        ),
    ]
