# Generated by Django 5.1.15 on 2026-09-29 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("direktur", "0002_decision"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audititem",
            name="pic_function",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SHIFT_COORDINATOR", "Koordinator Shift"),
                    ("CASHIER", "PIC Kasir"),
                    ("ONLINE", "Koordinator Layanan Daring"),
                    ("CLEANLINESS", "PJ Kebersihan dan Sterilitas"),
                    ("PHARMACY", "PIC Apotek"),
                ],
                default="",
                help_text="Penerima bawaan task temuan. Kosong berarti dipilih manual saat mencatat temuan.",
                max_length=32,
                verbose_name="fungsi PIC tindak lanjut",
            ),
        ),
    ]
