# Generated by Django 5.1.15 on 2026-09-30 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("direktur", "0003_pic_labels"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailySummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="tanggal")),
                ("note", models.TextField(blank=True, verbose_name="catatan Direktur")),
                ("content", models.JSONField(default=dict, verbose_name="isi")),
                (
                    "first_sent_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="pertama dikirim"
                    ),
                ),
                ("sent_at", models.DateTimeField(verbose_name="terakhir dikirim")),
                (
                    "send_count",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="berapa kali dikirim"
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="daily_summaries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "summary harian",
                "verbose_name_plural": "summary harian",
                "ordering": ("-date",),
            },
        ),
    ]
