# Generated by Django 5.1.15 on 2026-10-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_clinic_profile_data"),
        ("direktur", "0004_dailysummary"),
    ]

    operations = [
        migrations.AddField(
            model_name="decision",
            name="waiting_tasks",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tenggat task ini dibekukan selama keputusan belum diambil (K-015).",
                related_name="waiting_decisions",
                to="core.actionitem",
                verbose_name="task yang menunggu keputusan ini",
            ),
        ),
        migrations.AlterField(
            model_name="decision",
            name="decider",
            field=models.CharField(
                choices=[
                    ("RAPAT_BERSAMA", "Rapat bersama (Kamis)"),
                    ("OWNER", "Owner"),
                    ("DIRUT", "Direktur Utama"),
                    ("DIREKTUR_OPERASIONAL", "Direktur Operasional"),
                    ("PJ_PELAYANAN", "Penanggung Jawab Pelayanan"),
                    ("LAINNYA", "Lainnya"),
                ],
                max_length=24,
                verbose_name="diputuskan oleh",
            ),
        ),
    ]
