# Generated by Django 5.1.15 on 2026-10-06 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direktur', '0005_keputusan_rapat_bersama'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='decided_by',
            field=models.ForeignKey(blank=True, help_text='Owner yang memutuskan lewat halaman Owner (7 Okt 2026).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='decision',
            name='verdict',
            field=models.CharField(blank=True, choices=[('SETUJU', 'Disetujui'), ('TOLAK', 'Ditolak')], max_length=10, verbose_name='jawaban Owner'),
        ),
    ]
