# Generated by Django 5.1.15 on 2026-10-06 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direktur', '0006_keputusan_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySummaryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='tanggapan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='direktur.dailysummary')),
            ],
            options={
                'verbose_name': 'tanggapan summary',
                'verbose_name_plural': 'tanggapan summary',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='DailySummaryRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(verbose_name='terakhir dibuka')),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='direktur.dailysummary')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'tanda baca summary',
                'verbose_name_plural': 'tanda baca summary',
                'constraints': [models.UniqueConstraint(fields=('summary', 'user'), name='uniq_summary_read')],
            },
        ),
    ]
