# Generated by Django 5.1.15 on 2026-10-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direktur', '0007_summary_dua_arah'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='owner_only',
            field=models.BooleanField(default=False, help_text='Kebijakan hanya terlihat oleh Owner dan Direktur Operasional, tidak diumumkan ke staf.', verbose_name='hanya Owner'),
        ),
        migrations.AddField(
            model_name='decision',
            name='policy_group',
            field=models.CharField(choices=[('KLINIK', 'Klinik'), ('APOTEK', 'Apotek'), ('SEMUA', 'Semua staf')], default='SEMUA', max_length=8, verbose_name='kelompok kebijakan'),
        ),
    ]
