# Generated by Django 5.1.15 on 2026-09-29 01:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0005_clinic_profile_data"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DutyPortion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=40, verbose_name="kode")),
                ("name", models.CharField(max_length=120, verbose_name="nama")),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("OPENING", "Opening"),
                            ("CLOSING", "Closing"),
                            ("KEBERSIHAN", "Kebersihan"),
                            ("LIMBAH", "Limbah"),
                            ("KAS", "Kas"),
                            ("APOTEK", "Apotek"),
                        ],
                        max_length=12,
                        verbose_name="kelompok",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="isi singkat"),
                ),
                (
                    "eligible_roles",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Kosong berarti seluruh staf yang bertugas.",
                        verbose_name="peran yang boleh",
                    ),
                ),
                (
                    "pic_function",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SHIFT_COORDINATOR", "Koordinator Shift"),
                            ("CASHIER", "PIC Kasir"),
                            ("ONLINE", "Koordinator Layanan Daring"),
                            ("CLEANLINESS", "PJ Kebersihan dan Sterilitas"),
                            ("PHARMACY", "PIC Apotek"),
                        ],
                        default="",
                        help_text="Bila pemegang fungsi ini bertugas, porsi diberikan kepadanya; bila tidak, didelegasikan bergilir.",
                        max_length=32,
                        verbose_name="didahulukan untuk PIC",
                    ),
                ),
                (
                    "people",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="jumlah orang"
                    ),
                ),
                (
                    "weekdays",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="0=Senin … 6=Minggu. Kosong berarti setiap hari.",
                        verbose_name="hari",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="aktif")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="urutan"),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duty_portions",
                        to="core.clinic",
                    ),
                ),
            ],
            options={
                "verbose_name": "porsi tugas",
                "verbose_name_plural": "porsi tugas",
                "ordering": ("clinic_id", "sort_order", "code"),
            },
        ),
        migrations.CreateModel(
            name="DutyAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="tanggal")),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("OTOMATIS", "Disusun otomatis"),
                            ("MANUAL", "Diubah manual"),
                        ],
                        default="OTOMATIS",
                        max_length=10,
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="catatan"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duty_assignments",
                        to="core.clinic",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="duty_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "portion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="jadwal.dutyportion",
                    ),
                ),
            ],
            options={
                "verbose_name": "pembagian tugas",
                "verbose_name_plural": "pembagian tugas",
                "ordering": ("date", "portion__sort_order", "user__username"),
            },
        ),
        migrations.CreateModel(
            name="DutyRoster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="tanggal")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("MASUK", "Masuk"),
                            ("PERBANTUAN", "Perbantuan ke cabang lain"),
                            ("OFF", "Off"),
                            ("CUTI", "Cuti"),
                        ],
                        default="MASUK",
                        max_length=12,
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="catatan"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        blank=True,
                        help_text="Kosong bila off atau cuti.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="duty_days",
                        to="core.clinic",
                        verbose_name="bertugas di",
                    ),
                ),
                (
                    "home_clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="duty_home_days",
                        to="core.clinic",
                        verbose_name="cabang asal",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="duty_days",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "jadwal jaga",
                "verbose_name_plural": "jadwal jaga",
                "ordering": ("date", "home_clinic_id", "user__username"),
            },
        ),
        migrations.AddConstraint(
            model_name="dutyportion",
            constraint=models.UniqueConstraint(
                fields=("clinic", "code"), name="uniq_duty_portion_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="dutyassignment",
            constraint=models.UniqueConstraint(
                fields=("portion", "date", "user"), name="uniq_duty_assignment"
            ),
        ),
        migrations.AddConstraint(
            model_name="dutyroster",
            constraint=models.UniqueConstraint(
                fields=("user", "date"), name="uniq_duty_user_date"
            ),
        ),
    ]
