# Generated by Django 5.1.15 on 2026-09-10 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('AKSES_UMUM', 'Akses dan area umum'), ('KOMPUTER_SISTEM', 'Komputer dan sistem'), ('RUANG_KONSULTASI', 'Ruang konsultasi'), ('RUANG_TINDAKAN', 'Ruang tindakan estetik')], max_length=24)),
                ('template_snapshot', models.JSONField()),
                ('status', models.CharField(choices=[('BERJALAN', 'Berjalan'), ('SELESAI', 'Selesai'), ('DITERIMA_DENGAN_CATATAN', 'Diterima dengan catatan')], default='BERJALAN', max_length=26)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('exception_reason', models.TextField(blank=True, verbose_name='alasan pengecualian')),
                ('operational_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_runs', to='core.operationalday')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'checklist harian',
                'verbose_name_plural': 'checklist harian',
                'ordering': ('area',),
            },
        ),
        migrations.CreateModel(
            name='ChecklistResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_snapshot', models.JSONField()),
                ('label', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('required', models.BooleanField(default=True)),
                ('input_type', models.CharField(choices=[('CEKLIS', 'Ceklis'), ('KUANTITAS', 'Jumlah (kuantitas)')], default='CEKLIS', max_length=12)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('min_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('photo_required', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('result', models.CharField(choices=[('BELUM', 'Belum dicek'), ('OK', 'OK'), ('TIDAK_LENGKAP', 'Tidak lengkap'), ('RUSAK', 'Rusak'), ('TIDAK_BERLAKU', 'Tidak berlaku')], default='BELUM', max_length=16)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='jumlah aktual')),
                ('note', models.TextField(blank=True, verbose_name='catatan')),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_responses', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='checklists.checklistrun')),
            ],
            options={
                'verbose_name': 'respons checklist',
                'verbose_name_plural': 'respons checklist',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nama')),
                ('area', models.CharField(choices=[('AKSES_UMUM', 'Akses dan area umum'), ('KOMPUTER_SISTEM', 'Komputer dan sistem'), ('RUANG_KONSULTASI', 'Ruang konsultasi'), ('RUANG_TINDAKAN', 'Ruang tindakan estetik')], max_length=24, verbose_name='area')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='versi')),
                ('active', models.BooleanField(default=True, verbose_name='aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='core.clinic')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'template checklist',
                'verbose_name_plural': 'template checklist',
                'ordering': ('area', '-version'),
            },
        ),
        migrations.AddField(
            model_name='checklistrun',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='checklists.checklisttemplate'),
        ),
        migrations.CreateModel(
            name='ChecklistTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='item')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='kategori')),
                ('required', models.BooleanField(default=True, verbose_name='wajib')),
                ('input_type', models.CharField(choices=[('CEKLIS', 'Ceklis'), ('KUANTITAS', 'Jumlah (kuantitas)')], default='CEKLIS', max_length=12)),
                ('unit', models.CharField(blank=True, max_length=30, verbose_name='satuan')),
                ('min_quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='jumlah minimum')),
                ('photo_required', models.BooleanField(default=False, verbose_name='foto wajib')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('help_text', models.CharField(blank=True, max_length=250, verbose_name='petunjuk')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='checklists.checklisttemplate')),
            ],
            options={
                'verbose_name': 'item template',
                'verbose_name_plural': 'item template',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='checklisttemplate',
            constraint=models.UniqueConstraint(fields=('clinic', 'area', 'version'), name='uniq_template_area_version'),
        ),
        migrations.AddConstraint(
            model_name='checklistrun',
            constraint=models.UniqueConstraint(fields=('operational_day', 'area'), name='uniq_run_day_area'),
        ),
    ]
