# Generated by Django 5.1.15 on 2026-09-20 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0001_initial'),
        ('core', '0002_actionitem_assignment_mode_taskassignment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistFollowup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'tindak lanjut checklist',
                'verbose_name_plural': 'tindak lanjut checklist',
            },
        ),
        migrations.RemoveConstraint(
            model_name='checklistrun',
            name='uniq_run_day_area',
        ),
        migrations.RemoveConstraint(
            model_name='checklisttemplate',
            name='uniq_template_area_version',
        ),
        migrations.AddField(
            model_name='checklistrun',
            name='session',
            field=models.CharField(choices=[('OPENING', 'Pembukaan'), ('CLOSING', 'Penutupan'), ('ANYTIME', 'Kapan saja')], default='OPENING', max_length=12, verbose_name='sesi'),
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='assignment_mode',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('BERSAMA', 'Bersama')], default='INDIVIDUAL', max_length=12, verbose_name='mode assignment'),
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='session',
            field=models.CharField(choices=[('OPENING', 'Pembukaan'), ('CLOSING', 'Penutupan'), ('ANYTIME', 'Kapan saja')], default='OPENING', max_length=12, verbose_name='sesi'),
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='target_pic_function',
            field=models.CharField(blank=True, choices=[('SHIFT_COORDINATOR', 'Koordinator shift'), ('CASHIER', 'Kasir'), ('ONLINE', 'Online'), ('CLEANLINESS', 'Kebersihan')], default='', max_length=32, verbose_name='fungsi PIC target'),
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='target_role',
            field=models.CharField(blank=True, choices=[('STAF', 'Staf operasional'), ('FRONT_DESK', 'Front desk/kasir'), ('PERAWAT', 'Perawat'), ('SUPERVISOR', 'Supervisor'), ('PIC', 'PIC cabang'), ('AOM', 'AOM lintas cabang'), ('ADMIN', 'Admin'), ('OWNER', 'Owner/Manajemen')], default='', max_length=20, verbose_name='role/tier target'),
        ),
        migrations.AddConstraint(
            model_name='checklistrun',
            constraint=models.UniqueConstraint(fields=('operational_day', 'area', 'session'), name='uniq_run_day_area_session'),
        ),
        migrations.AddConstraint(
            model_name='checklisttemplate',
            constraint=models.UniqueConstraint(fields=('clinic', 'area', 'session', 'version'), name='uniq_template_area_session_version'),
        ),
        migrations.AddField(
            model_name='checklistfollowup',
            name='action_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_followups', to='core.actionitem'),
        ),
        migrations.AddField(
            model_name='checklistfollowup',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_followups_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checklistfollowup',
            name='response',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='followup', to='checklists.checklistresponse'),
        ),
    ]
