# Generated by Django 5.1.15 on 2026-09-20 08:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0002_aom_fase3_checklist'),
        ('core', '0002_actionitem_assignment_mode_taskassignment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='checklistrun',
            name='uniq_run_day_area_session',
        ),
        migrations.RemoveConstraint(
            model_name='checklisttemplate',
            name='uniq_template_area_session_version',
        ),
        migrations.AddField(
            model_name='checklistresponse',
            name='performer_roles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='checklistresponse',
            name='verifier_roles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='audience_key',
            field=models.CharField(blank=True, default='', help_text='Kunci unik template per peran/fungsi; kosong untuk template lama.', max_length=40, verbose_name='kunci target'),
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='target_roles',
            field=models.JSONField(blank=True, default=list, help_text='Daftar role yang dapat melihat/mengisi run checklist.', verbose_name='role target'),
        ),
        migrations.AddField(
            model_name='checklisttemplateitem',
            name='performer_roles',
            field=models.JSONField(blank=True, default=list, verbose_name='role pelaksana'),
        ),
        migrations.AddField(
            model_name='checklisttemplateitem',
            name='verifier_roles',
            field=models.JSONField(blank=True, default=list, verbose_name='role verifikator'),
        ),
        migrations.AlterField(
            model_name='checklisttemplate',
            name='target_role',
            field=models.CharField(blank=True, choices=[('STAF', 'Staf operasional'), ('FRONT_DESK', 'Front desk/kasir'), ('PERAWAT', 'Perawat'), ('APOTEKER', 'Apoteker'), ('ONLINE', 'Online/reservasi'), ('SUPERVISOR', 'Supervisor'), ('PIC', 'PIC cabang'), ('AOM', 'AOM lintas cabang'), ('ADMIN', 'Admin'), ('OWNER', 'Owner/Manajemen')], default='', max_length=20, verbose_name='role/tier target'),
        ),
        migrations.AddConstraint(
            model_name='checklistrun',
            constraint=models.UniqueConstraint(fields=('operational_day', 'template'), name='uniq_run_day_template'),
        ),
        migrations.AddConstraint(
            model_name='checklisttemplate',
            constraint=models.UniqueConstraint(fields=('clinic', 'area', 'session', 'version', 'audience_key'), name='uniq_template_area_session_version_audience'),
        ),
    ]
