# Generated by Django 5.1.15 on 2026-09-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0003_remove_checklistrun_uniq_run_day_area_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistresponse',
            name='options',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='checklistresponse',
            name='selection',
            field=models.CharField(blank=True, max_length=80, verbose_name='pilihan'),
        ),
        migrations.AddField(
            model_name='checklisttemplateitem',
            name='options',
            field=models.JSONField(blank=True, default=list, verbose_name='opsi pilihan'),
        ),
        migrations.AlterField(
            model_name='checklistresponse',
            name='input_type',
            field=models.CharField(choices=[('CEKLIS', 'Ceklis'), ('KUANTITAS', 'Jumlah (kuantitas)'), ('PILIHAN', 'Pilihan')], default='CEKLIS', max_length=12),
        ),
        migrations.AlterField(
            model_name='checklisttemplate',
            name='target_pic_function',
            field=models.CharField(blank=True, choices=[('SHIFT_COORDINATOR', 'Koordinator shift'), ('CASHIER', 'Koordinator kasir'), ('ONLINE', 'Koordinator online'), ('CLEANLINESS', 'Kebersihan')], default='', max_length=32, verbose_name='fungsi PIC target'),
        ),
        migrations.AlterField(
            model_name='checklisttemplate',
            name='target_role',
            field=models.CharField(blank=True, choices=[('STAF', 'Staf operasional'), ('FRONT_DESK', 'Front desk/kasir'), ('PERAWAT', 'Perawat'), ('APOTEKER', 'Apoteker'), ('ASISTEN_APOTEKER', 'Asisten apoteker'), ('ONLINE', 'Koordinator online'), ('SUPERVISOR', 'Koordinator shift'), ('PIC', 'PIC cabang'), ('AOM', 'AOM lintas cabang'), ('ADMIN', 'Admin'), ('OWNER', 'Owner/Manajemen')], default='', max_length=20, verbose_name='role/tier target'),
        ),
        migrations.AlterField(
            model_name='checklisttemplateitem',
            name='input_type',
            field=models.CharField(choices=[('CEKLIS', 'Ceklis'), ('KUANTITAS', 'Jumlah (kuantitas)'), ('PILIHAN', 'Pilihan')], default='CEKLIS', max_length=12),
        ),
    ]
