# Generated by Django 5.1.15 on 2026-09-29 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checklists", "0004_checklistresponse_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="checklistresponse",
            name="portion",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="checklisttemplateitem",
            name="portion",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Kode porsi pada pembagian tugas harian (jadwal.DutyPortion). Kosong bila tidak dibagi.",
                max_length=40,
                verbose_name="porsi tugas",
            ),
        ),
        migrations.AlterField(
            model_name="checklistresponse",
            name="input_type",
            field=models.CharField(
                choices=[
                    ("CEKLIS", "Ceklis"),
                    ("KUANTITAS", "Jumlah (kuantitas)"),
                    ("PILIHAN", "Pilihan"),
                    ("JAM", "Jam (JJ:MM)"),
                ],
                default="CEKLIS",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="checklistrun",
            name="area",
            field=models.CharField(
                choices=[
                    ("AKSES_UMUM", "Akses dan area umum"),
                    ("KOMPUTER_SISTEM", "Komputer dan sistem"),
                    ("RUANG_KONSULTASI", "Ruang konsultasi"),
                    ("RUANG_TINDAKAN", "Ruang tindakan estetik"),
                    ("KEBERSIHAN", "Kebersihan dan piket"),
                    ("LIMBAH", "Limbah medis"),
                    ("KAS", "Kas"),
                    ("APOTEK", "Apotek"),
                ],
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="checklisttemplate",
            name="area",
            field=models.CharField(
                choices=[
                    ("AKSES_UMUM", "Akses dan area umum"),
                    ("KOMPUTER_SISTEM", "Komputer dan sistem"),
                    ("RUANG_KONSULTASI", "Ruang konsultasi"),
                    ("RUANG_TINDAKAN", "Ruang tindakan estetik"),
                    ("KEBERSIHAN", "Kebersihan dan piket"),
                    ("LIMBAH", "Limbah medis"),
                    ("KAS", "Kas"),
                    ("APOTEK", "Apotek"),
                ],
                max_length=24,
                verbose_name="area",
            ),
        ),
        migrations.AlterField(
            model_name="checklisttemplate",
            name="target_pic_function",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SHIFT_COORDINATOR", "Koordinator Shift"),
                    ("CASHIER", "PIC Kasir"),
                    ("ONLINE", "Koordinator Layanan Daring"),
                    ("CLEANLINESS", "PJ Kebersihan dan Sterilitas"),
                    ("PHARMACY", "PIC Apotek"),
                ],
                default="",
                max_length=32,
                verbose_name="fungsi PIC target",
            ),
        ),
        migrations.AlterField(
            model_name="checklisttemplate",
            name="target_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("STAF", "Staf operasional"),
                    ("FRONT_DESK", "Front desk/kasir"),
                    ("PERAWAT", "Perawat"),
                    ("APOTEKER", "Apoteker"),
                    ("ASISTEN_APOTEKER", "Asisten apoteker"),
                    ("ONLINE", "Koordinator layanan daring"),
                    ("SUPERVISOR", "Koordinator shift"),
                    ("PIC", "PIC cabang"),
                    ("AOM", "Direktur Operasional"),
                    ("ADMIN", "Admin"),
                    ("OWNER", "Owner/Manajemen"),
                ],
                default="",
                max_length=20,
                verbose_name="role/tier target",
            ),
        ),
        migrations.AlterField(
            model_name="checklisttemplateitem",
            name="input_type",
            field=models.CharField(
                choices=[
                    ("CEKLIS", "Ceklis"),
                    ("KUANTITAS", "Jumlah (kuantitas)"),
                    ("PILIHAN", "Pilihan"),
                    ("JAM", "Jam (JJ:MM)"),
                ],
                default="CEKLIS",
                max_length=12,
            ),
        ),
    ]
