# Generated by Django 5.1.15 on 2026-09-30 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checklists", "0005_portion_jam_areas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checklisttemplate",
            name="target_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("STAF", "Staf operasional"),
                    ("FRONT_DESK", "Front desk/kasir"),
                    ("PERAWAT", "Perawat"),
                    ("APOTEKER", "Apoteker"),
                    ("ASISTEN_APOTEKER", "Asisten apoteker"),
                    ("ONLINE", "Koordinator layanan daring"),
                    ("SUPERVISOR", "Koordinator shift"),
                    ("PIC", "PIC cabang"),
                    ("AOM", "Direktur Operasional"),
                    ("ADMIN", "Admin"),
                    ("OWNER", "Owner / Direktur Utama"),
                ],
                default="",
                max_length=20,
                verbose_name="role/tier target",
            ),
        ),
    ]
