# Generated by Django 5.1.15 on 2026-09-20 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_actionitem_assignment_mode_taskassignment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=24, unique=True)),
                ('customer_name', models.CharField(max_length=120, verbose_name='nama pelanggan')),
                ('customer_contact', models.CharField(max_length=80, verbose_name='kontak pelanggan')),
                ('product_name', models.CharField(max_length=160, verbose_name='produk')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='jumlah')),
                ('note', models.TextField(blank=True, verbose_name='catatan')),
                ('status', models.CharField(choices=[('BARU', 'Baru'), ('DIPROSES', 'Diproses apoteker'), ('SIAP', 'Siap diambil/dikirim'), ('SELESAI', 'Selesai'), ('BATAL', 'Dibatalkan')], default='BARU', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='online_orders', to='core.clinic')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='online_orders_created', to=settings.AUTH_USER_MODEL)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='online_orders_handled', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
