# Generated by Django 5.1.15 on 2026-09-20 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineorder',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='total'),
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='harga satuan'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=80, verbose_name='golongan')),
                ('name', models.CharField(max_length=180, verbose_name='nama produk')),
                ('ingredient', models.CharField(blank=True, max_length=240, verbose_name='kandungan')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='harga jual')),
                ('active', models.BooleanField(default=True, verbose_name='aktif')),
                ('source', models.CharField(default='LIST PRODUK JODERMA.xlsx', max_length=120)),
            ],
            options={
                'ordering': ('category', 'name'),
                'constraints': [models.UniqueConstraint(fields=('category', 'name'), name='uniq_product_category_name')],
            },
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='online_orders', to='orders.product'),
        ),
    ]
