# Generated by Django 5.1.15 on 2026-09-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_onlineorder_total_price_onlineorder_unit_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineorder',
            name='customer_address',
            field=models.TextField(blank=True, default='', verbose_name='alamat pemesan'),
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='rm_number',
            field=models.CharField(blank=True, default='J_-', max_length=32, verbose_name='nomor RM'),
        ),
    ]
