# Generated by Django 5.1.15 on 2026-09-21 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_onlineorder_customer_address_onlineorder_rm_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft belum dikirim'), ('BARU', 'Baru'), ('DIPROSES', 'Diproses apoteker'), ('SIAP', 'Siap diambil/dikirim'), ('SELESAI', 'Selesai'), ('BATAL', 'Dibatalkan')], default='BARU', max_length=12),
        ),
        migrations.CreateModel(
            name='OnlineOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=160, verbose_name='produk')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='jumlah')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='harga satuan')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='subtotal')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.onlineorder')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='orders.product')),
            ],
        ),
    ]
