# Generated by Django 5.1.15 on 2026-09-10 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_code', models.CharField(db_index=True, max_length=40)),
                ('title', models.CharField(max_length=160)),
                ('body', models.CharField(blank=True, max_length=300)),
                ('entity_ref', models.CharField(blank=True, db_index=True, max_length=60)),
                ('url', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notifikasi',
                'verbose_name_plural': 'notifikasi',
                'ordering': ('-created_at',),
            },
        ),
    ]
